### ISSUE TITLE
I get the following error trying to run CSteamworks2.py following the instructions in the readme

### ISSUE THREAD

**Issue by zacharycarter** [rlabrecque/CSteamworks#12]
```
Traceback (most recent call last):
  File "CSteamworks2.py", line 119, in <module>
    main()
  File "CSteamworks2.py", line 41, in main
    parser = steamworksparser.parse("steam/")
  File "/Users/zachcarter/projects/CSteamworks/SteamworksParser/steamworksparser.py", line 873, in parse
    return Parser(folder)
  File "/Users/zachcarter/projects/CSteamworks/SteamworksParser/steamworksparser.py", line 224, in __init__
    with open(filepath, 'r', encoding="latin-1") as infile:
TypeError: 'encoding' is an invalid keyword argument for this function
```

OSX, python 2.7.13

**Comment by zacharycarter** [comment]
Nevermind I didn't realize SteamworksParser required Python3

**Comment by rlabrecque** [comment]
Sorry for not including that! I'm curious what you're using CSteamworks for? At this point I'd probably recommend using Valve's C API, and Steamworks .NET has switched over to it now.
